# Generated by Django 4.1.1 on 2022-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id_calle', models.BigAutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'calle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id_flujo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_flujo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'flujo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id_jerarquia', models.BigAutoField(primary_key=True, serialize=False)),
                ('jerarquia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jerarquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('tarea', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1024)),
                ('fecha_inicio', models.DateField()),
                ('fecha_plazo', models.DateField()),
                ('porcentaje_cumplido', models.BigIntegerField()),
                ('reporte', models.CharField(blank=True, max_length=1024, null=True)),
                ('aprobacion', models.CharField(blank=True, max_length=1, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
    ]
