# Generated by Django 4.1.1 on 2022-11-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_calle_ciudad_comuna_estado_flujo_jerarquia_persona_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
